<a href="https://colab.research.google.com/github/S-ABARNA/Artificial-Intelligence-Lab/blob/main/EX%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random
from time import sleep

def create_board():
    return np.zeros((3, 3), dtype=int)

def possibilities(board):
    return [(i, j) for i in range(3) for j in range(3) if board[i, j] == 0]

def random_place(board, player):
    selection = possibilities(board)
    if selection:
        current_loc = random.choice(selection)
        board[current_loc] = player
    return board

def check_win(board, player):
    return (
        any(np.all(board == player, axis=0)) or  # Check rows
        any(np.all(board == player, axis=1)) or  # Check columns
        np.all(np.diag(board) == player) or  # Check main diagonal
        np.all(np.diag(np.fliplr(board)) == player)  # Check secondary diagonal
    )

def evaluate(board):
    for player in [1, 2]:
        if check_win(board, player):
            return player
    return -1 if np.all(board != 0) else 0

def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    sleep(2)

    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print(f"Board after {counter} move:")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break

    return winner

# Driver Code
print("Winner is:", play_game())


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move:
[[0 0 0]
 [0 0 1]
 [0 0 0]]
Board after 2 move:
[[0 0 0]
 [0 0 1]
 [0 2 0]]
Board after 3 move:
[[0 0 1]
 [0 0 1]
 [0 2 0]]
Board after 4 move:
[[0 0 1]
 [0 0 1]
 [0 2 2]]
Board after 5 move:
[[0 0 1]
 [0 0 1]
 [1 2 2]]
Board after 6 move:
[[0 0 1]
 [0 2 1]
 [1 2 2]]
Board after 7 move:
[[0 1 1]
 [0 2 1]
 [1 2 2]]
Board after 8 move:
[[0 1 1]
 [2 2 1]
 [1 2 2]]
Board after 9 move:
[[1 1 1]
 [2 2 1]
 [1 2 2]]
Winner is: 1
